### ISSUE TITLE
Doesnt Show Devices - restoreIot

### ISSUE THREAD

**Issue by knaueranthony** [dgreif/homebridge-hatch-baby-rest#99]
Having an issue where after credentials are added none of my devices are showing in HB or Homekit. Keep getting
[1/21/2023, 1:41:38 PM] [homebridge-hatch-baby-rest] Loaded homebridge-hatch-baby-rest v4.0.0 child bridge successfully
[1/21/2023, 1:41:43 PM] [homebridge-hatch-baby-rest] Unsupported Product Found: alexa
[1/21/2023, 1:41:43 PM] [homebridge-hatch-baby-rest] Unsupported Product Found: restoreIot
[1/21/2023, 1:41:43 PM] [homebridge-hatch-baby-rest] Configuring 0 Rest+, 0 Rest Mini, 0 Rest 2nd Gen, 0 Rest+ 2nd Gen, and 0 Restore

Thanks In advance

**Comment by dgreif** [comment]
Looks like you have a `restoreIot`, which is a newer version of the Restore. In https://github.com/dgreif/homebridge-hatch-baby-rest/issues/74, this device type didn't appear to match the data structure of the original restore. I'll need to update the code to allow it again, but I don't have a good example of the data structure yet.

For transparency, this is a pretty low priority for me. I'm not sure when I'll get to it, but PRs are welcome if anyone has a `restoreIot` and is able to update the plugin to handle it.

**Comment by knaueranthony** [comment]
Thanks for taking the time to answer this. I also have a rest too which isn’t connecting either. It’s not even showing. Appreciate all the help and have a blessed day.

**Comment by dgreif** [comment]
Is the Rest the bluetooth version or wifi? If bluetooth, you will need to install the [homebridge-hatch-rest-bluetooth](https://github.com/dgreif/homebridge-hatch-baby-rest/tree/main/packages/homebridge-hatch-rest-bluetooth) plugin and configure it separately

**Comment by mpatfield** [comment]
@dgreif if you point me in the right direction I can try to get you an example of the data structure. Is there an easy way to capture that?

**Comment by evbarnett5** [comment]
For reference I had experimented with this late last year. Unfortunately I redid my homebridge config a few months ago so and the changes got overwritten. From my memory

1. Edit api.ts to match the name that the hatch API responded with (restoreIot)

2. Modify iot-device.ts to output the MQTT messages sent to console, text file, etc. Should be in the    mqttClient.on('foreignStateChange', (topic, message, s) function. 

3. Turn restore on and off using the app to show activity on the mqtt broker. 

There may have been one or two items I had to comment out but I can't remember them. When I started to mess with the data structure and send my own commands to the broker I think I locked the restore and it severely limited its functionality (alarms weren't going off, couldn't edit was times or routines, etc.) so beware of that. Had to reach out to customer support to get the hard reset process. Again, sorry I can't provide a PR but hope this helps.

**Comment by bpro** [comment]
hi friends!

i recently picked up a `restoreIot` device and did the work to intercept the MQTT messages: [[PR on fork for visibility](https://github.com/bpro/homebridge-hatch-baby-rest/pull/1)]

i then intercepted messages for turning on the first step in my sleep routine: [routine_step_1.log](https://github.com/dgreif/homebridge-hatch-baby-rest/files/11493145/routine_step_1.log)

and intercepted messages for turning the restore back off: 
[off.log](https://github.com/dgreif/homebridge-hatch-baby-rest/files/11493147/off.log)

(note: my [code](https://github.com/bpro/homebridge-hatch-baby-rest/blob/7e9492e92a698e5c5389623b0405dc7fdfbeef94/packages/homebridge-hatch-baby-rest/iot-device.ts#L94) also prints out the `currentState` - i know this is probably less useful for you, but it was educational for me)

**Comment by bpro** [comment]
okay i think i got basic `restoreIot` ON/OFF support working: [pull request](https://github.com/dgreif/homebridge-hatch-baby-rest/pull/106)

it's quick & dirty - seems like there's heavy overlap between `RestIot` and `RestoreIot` - we could probably reuse more logic between the two

but let me know if you're interested in trying to merge this in (and if so, i'm happy to do a little cleanup - just drop comments)

**Comment by dgreif** [comment]
I just released v`4.2.0` which _should_ work with the `restoreIot`. Huge thanks to @bpro for investigating and opening the initial PR. It looks like this device uses a setup very similar to the `restIot`, so I just merged everything into that setup. @knaueranthony @mpatfield @bpro  let me know if you have a chance to upgrade it give it a try!

Note: this device uses complex routines, so you will only receive a single on/off toggle. When turned on, it will activate the first routine on the device (first thing that runs when you touch the button on the Restore)

**Comment by mpatfield** [comment]
+1 thanks @bpro for working on this!

And thanks @dgreif for the merge/release. I know this isn't a high priority for you, but it's really appreciated.

Unfortunately, it still doesn't seem to be working for me in `v4.2.0`

> <img width="686" alt="Screenshot 2024-02-05 at 8 26 21 AM" src="https://github.com/dgreif/homebridge-hatch-baby-rest/assets/18125347/fa9c633d-c473-4df2-b563-bec590175e46">

Not sure if this is something specific to my setup so I can wait for the others to try it.

In the meantime, let me know if there's any additional info I can provide to help debug. I'm not fluent in TypeScript or HB plugin development, but I do have a technical background so I can probably grab whatever info you need with a bit of handholding.

**Comment by dgreif** [comment]
Thanks for the update @mpatfield! Looks like your device is the `restoreV4`, while others in this thread are seeing the `restoreIot`. I'm honestly not sure what the difference is since I only see the `Restore 2` on Hatch's website. Whats the name of the model/product you have?

**Comment by mpatfield** [comment]
I have the [Hatch Restore 2](https://www.hatch.co/restore-2) so no idea why it's showing as `restoreV4`. Maybe some internal designation? 🤷‍♂️

When I was on an older version of the plugin (`v4.0.1`) I saw `restoreIot` in the logs in addition to `restoreV4`.

`[04/02/2024, 21:22:281 [HatchBabyRest] Unsupported Product Found: alexa`
`[04/02/2024, 21:22:281 [HatchBabyRest] Unsupported Product Found: restoreV4`
`[04/02/2024, 21:22:281 [HatchBabyRest] Unsupported Product Found: restorelot`
`[04/02/2024, 21:22:281 [HatchBabyRest] Configuring 0 Restt, 0 Rest Mini, 0 Rest 2nd Gen, 0 Rest 2nd Gen, and 0 Restore`

Just to be clear, I only have one device. Really curious if `v4.2.0` work for either @knaueranthony or @bpro and, if so, which Hatch device they have.

**Comment by dgreif** [comment]
@mpatfield let's move the discussion about `restoreV4` over to #104. @knaueranthony @bpro I'm still interested to hear if the latest version works with your `restoreIot` device 🤞

**Comment by evbarnett5** [comment]
I have been on travel for work this week but I just pulled down latest version and tested on restoreIot, worked on my end. Thanks @dgreif and @bpro!
